[package]
name = "roturb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.1"
gauss-quad = "0.1.7"
itertools = "0.12.0"
nalgebra = "0.32.3"
